### ISSUE TITLE
'ForgeParams4bit' object has no attribute 'quant_storage'

### ISSUE THREAD

**Issue by FLYleoYBQ** [comfyanonymous/ComfyUI_bitsandbytes_NF4#1]
![屏幕截图 2024-08-11 225011](https://github.com/user-attachments/assets/ef51bb9d-be82-4c01-a1a0-296dfec24038)
'ForgeParams4bit' object has no attribute 'quant_storage'

**Comment by FLYleoYBQ** [comment]
After pip install -U bitsandbytes, it starts to work properly, thank you very much indeed for your work

**Comment by FLYleoYBQ** [comment]
> ![屏幕截图 2024-08-11 225011](https://private-user-images.githubusercontent.com/91361597/356886070-ef51bb9d-be82-4c01-a1a0-296dfec24038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODg5OTgsIm5iZiI6MTcyMzM4ODY5OCwicGF0aCI6Ii85MTM2MTU5Ny8zNTY4ODYwNzAtZWY1MWJiOWQtYmU4Mi00YzAxLWExYTAtMjk2ZGZlYzI0MDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1MDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MDNkNDExYThmMjYzNGNiMzY4NzJmOTI2N2VmNDMzNjkzOGM5NDU4NzRiOTQzYzlmY2MwZDI1NWI5ZWZkNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wkOeR30Ag0d9Y2xytDJB04v3qu3YPOy-Oey4TNCXVZo) 'ForgeParams4bit' 对象没有属性 'quant_storage'

After pip install -U bitsandbytes, it starts to work properly, thank you very much indeed for your work

**Comment by An-Gz** [comment]
Same here, but different console output on Mac (M3 Max),  pip install -U bitsandbytes done. Any chance will be supported for OSX metal architecture? Thanks!

<img width="835" alt="Screenshot 2024-08-11 at 23 37 38" src="https://github.com/user-attachments/assets/45c91b4d-c6f9-4910-9098-e5f83f9caa37">

**Comment by ameen-roayan** [comment]
another variant 
![image](https://github.com/user-attachments/assets/fe509ec7-a302-4bf7-896e-45a84dfdd894)

**Comment by wangwangwangwangwei** [comment]
I am a beginner, please tell me which file to use "pip install -U bitsandbytes"

**Comment by PopHorn** [comment]
Same here. bitsandbytes installed. All up to date.

**Comment by Moardread** [comment]
Same error, have everything installed, tried multiple workflows as well. also have bitsandbytes installed and working in other code.
Tried reinstall, updates, same issue.

**Comment by comfyanonymous** [comment]
The "quant_storage" issue is because you need to update bitsandbytes, the "model_options" issue is because you need to update ComfyUI.

**Comment by PopHorn** [comment]
> The "quant_storage" issue is because you need to update bitsandbytes, the "model_options" issue is because you need to update ComfyUI.

Yes. The NEW version (25 min old) node version working for me. Thank you.

**Comment by cchance27** [comment]
i updated bitsandbytes and still getting same error about the quant_storage 

AttributeError: 'ForgeParams4bit' object has no attribute 'quant_storage'. Did you mean: 'quant_state'?

**Comment by Moardread** [comment]
> The "quant_storage" issue is because you need to update bitsandbytes, the "model_options" issue is because you need to update ComfyUI.

I have 0.43.3 and I still get the same error message about "quant_storage". I have reinstalled bitsandbytes using 2 methods, same issue. I have updated Comfy and reinstalled the requirements.txt a few times. Not sure what is wrong...
I also tried 0.43.0 as is in the requirements folder. Same issue.
Also tried restarting PC after reinstalling bitsandbytes.

**Comment by speadskater** [comment]
![error](https://github.com/user-attachments/assets/a484b306-24a3-41e4-a51f-f9f0d6775d20)

Getting the same error.  Reinstalled the requirements, updated comfy, etc.

**Comment by 7enChan** [comment]
> Same here, but different console output on Mac (M3 Max), pip install -U bitsandbytes done. Any chance will be supported for OSX metal architecture? Thanks!
> 
> <img alt="Screenshot 2024-08-11 at 23 37 38" width="835" src="https://private-user-images.githubusercontent.com/77484209/356889117-45c91b4d-c6f9-4910-9098-e5f83f9caa37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjA3MDIsIm5iZiI6MTcyMzQyMDQwMiwicGF0aCI6Ii83NzQ4NDIwOS8zNTY4ODkxMTctNDVjOTFiNGQtYzZmOS00OTEwLTkwOTgtZTVmODNmOWNhYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDIzNTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZjY3Njk2NzdmZGY4YTg1NWUzNzZhMTc0ODJjMWEyYmY0YmRkZDE4NmMzM2QyODBmYTcxN2YxMDM2NTYzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWAwdV8EVxnDylcdqPccTiJTcjm1b5ysIo7WCMBh180">

bitsandbytes Currently not supported on macOS: https://huggingface.co/docs/bitsandbytes/v0.43.3/en/installation#cuda

**Comment by merc4derp** [comment]
Comfy uses an embedded python installation. You need to run pip through there. The command is:

 [comfy install dir]\python_embedded\python -m pip install -U bitsandbytes

Restart comfyui afterwards.

**Comment by An-Gz** [comment]
> > Same here, but different console output on Mac (M3 Max), pip install -U bitsandbytes done. Any chance will be supported for OSX metal architecture? Thanks!
> > <img alt="Screenshot 2024-08-11 at 23 37 38" width="835" src="https://private-user-images.githubusercontent.com/77484209/356889117-45c91b4d-c6f9-4910-9098-e5f83f9caa37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjA3MDIsIm5iZiI6MTcyMzQyMDQwMiwicGF0aCI6Ii83NzQ4NDIwOS8zNTY4ODkxMTctNDVjOTFiNGQtYzZmOS00OTEwLTkwOTgtZTVmODNmOWNhYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDIzNTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZjY3Njk2NzdmZGY4YTg1NWUzNzZhMTc0ODJjMWEyYmY0YmRkZDE4NmMzM2QyODBmYTcxN2YxMDM2NTYzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWAwdV8EVxnDylcdqPccTiJTcjm1b5ysIo7WCMBh180">
> 
> bitsandbytes Currently not supported on macOS: https://huggingface.co/docs/bitsandbytes/v0.43.3/en/installation#cuda If your memory is not too small, you can ignore the low-precision version, Because Macs with Apple Silicon chips use a unified memory architecture, which means that the RAM is also the VRAM. On my M2Max 96GB Mac, the speeds of the 16fps and 8fps versions are basically the same (I tested it with Draw Things, the 8fps version doesn't work on ComfyUI). The best solution I am currently using on my Mac that balances speed and quality is to use the dev&schnell merged model(1:2.5 version) with just 4-8 steps.

M3 64gb here. 
Great info, will try the merged Flux and subscribe to the linked thread to follow metal dev for Bistansbytes. Thanks!

**Comment by hillleaf** [comment]
> I am a beginner, please tell me which file to use "pip install -U bitsandbytes"

![03ecff6e-7e3f-4179-acea-a26a08eb4be0](https://github.com/user-attachments/assets/3c4239a7-b4bf-4413-8fd1-b4ffbe098b37)

**Comment by danganbenpa** [comment]
The solution seems to be to pip install bits and bytes with the python.exe in either a python or a python_embedded folder in your comfyui folder which would be fine except I don't have either of those folders in my comfyui folder. If that's the case how do I solve this?

**Comment by xzuyn** [comment]
Seems like ROCm is effected by this since it uses [`multi-backend-refactor` branch](https://github.com/bitsandbytes-foundation/bitsandbytes/tree/multi-backend-refactor), and that's only 9 commits behind main.

**Comment by ProtoBelisarius** [comment]
Im currently stuck here as well, though that might be expected with ROCm.

I tried building https://github.com/ROCm/bitsandbytes, from this [official guide](https://rocm.docs.amd.com/en/latest/how-to/llm-fine-tuning-optimization/model-quantization.html), but thats still at 0.43.2, and even though the requirement.txt mentions bitsandbytes>=0.43.0, that doesnt seem to be correct.

With 0.43.2 I also get the `'ForgeParams4bit' object has no attribute 'quant_storage'` error.

I then tried forking it and merging the official commits into it, which worked without conflict, but just produces another error: `AttributeError: 'NoneType' object has no attribute 'cdequantize_blockwise_fp32'`
So even though its pretty much 0.43.3 it doesnt work.

No real idea about any of this though, just posting my futile efforts.

**Comment by xzuyn** [comment]
@ProtoBelisarius I got it working by merging in the commits.

https://github.com/xzuyn/bitsandbytes/tree/multi-backend-refactor

I use the huggingface guide to install: https://huggingface.co/docs/bitsandbytes/main/en/installation#amd-gpu

```
git clone --depth 1 -b multi-backend-refactor https://github.com/xzuyn/bitsandbytes.git && cd bitsandbytes
pip install -r requirements-dev.txt
apt-get install -y build-essential cmake
cmake -DCOMPUTE_BACKEND=hip -DBNB_ROCM_ARCH="gfx1100" -S .
make
pip install .
```

**Comment by ProtoBelisarius** [comment]
@xzuyn Thank you, but I ran into errors again.

During compile neither cmake or make put out any errors, they found my rocm install and everything else. 

But when I launch Comfy I get the following error just before it shows the loaded custom nodes. It doesnt prevent launching though.

```
Could not find the bitsandbytes CUDA binary at PosixPath('/home/username/Git/ComfyUI/venv/lib/python3.12/site-packages/bitsandbytes-0.43.3-py3.12-linux-x86_64.egg/bitsandbytes/libbitsandbytes_rocm61.so')
Could not load bitsandbytes native library: /home/username/Git/ComfyUI/venv/lib/python3.12/site-packages/bitsandbytes-0.43.3-py3.12-linux-x86_64.egg/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/username/Git/ComfyUI/venv/lib/python3.12/site-packages/bitsandbytes-0.43.3-py3.12-linux-x86_64.egg/bitsandbytes/cextension.py", line 126, in <module>
    lib = get_native_library()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/ComfyUI/venv/lib/python3.12/site-packages/bitsandbytes-0.43.3-py3.12-linux-x86_64.egg/bitsandbytes/cextension.py", line 104, in get_native_library
    dll = ct.cdll.LoadLibrary(str(binary_path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/username/Git/ComfyUI/venv/lib/python3.12/site-packages/bitsandbytes-0.43.3-py3.12-linux-x86_64.egg/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory

CUDA Setup failed despite CUDA being available. Please run the following command to get more information:

python -m bitsandbytes

Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

g++ (GCC) 14.2.1 20240805
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Error processing line 1 of /home/username/Git/ComfyUI/venv/lib/python3.12/site-packages/google_generativeai-0.7.2-py3.11-nspkg.pth:

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen site>", line 206, in addpackage
  File "<string>", line 1, in <module>
  File "/home/username/Git/ComfyUI/comfy/types.py", line 1, in <module>
    import torch
  File "/home/username/Git/ComfyUI/venv/lib/python3.12/site-packages/torch/__init__.py", line 16, in <module>
    import platform
  File "/usr/lib/python3.12/platform.py", line 118, in <module>
    import re
  File "/usr/lib/python3.12/re/__init__.py", line 124, in <module>
    import enum
  File "/usr/lib/python3.12/enum.py", line 3, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/home/username/Git/ComfyUI/comfy/types.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen site>", line 635, in <module>
  File "<frozen site>", line 618, in main
  File "<frozen site>", line 550, in venv
  File "<frozen site>", line 405, in addsitepackages
  File "<frozen site>", line 247, in addsitedir
  File "<frozen site>", line 216, in addpackage
  File "/usr/lib/python3.12/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.12/linecache.py", line 8, in <module>
    import functools
  File "/usr/lib/python3.12/functools.py", line 22, in <module>
    from types import GenericAlias
  File "/home/username/Git/ComfyUI/comfy/types.py", line 1, in <module>
    import torch
  File "/home/username/Git/ComfyUI/venv/lib/python3.12/site-packages/torch/__init__.py", line 16, in <module>
    import platform
  File "/usr/lib/python3.12/platform.py", line 118, in <module>
    import re
  File "/usr/lib/python3.12/re/__init__.py", line 124, in <module>
    import enum
  File "/usr/lib/python3.12/enum.py", line 3, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/home/username/Git/ComfyUI/comfy/types.py)
W0813 18:34:44.042000 139805771957952 torch/_inductor/compile_worker/subproc_pool.py:126] SubprocPool unclean exit
```
What I find confusing is that I have ROCm 6.2 installed but it asks for 6.1 in the error message even though cmake used the stuff from 6.2.

**Comment by xzuyn** [comment]
@ProtoBelisarius sorry, idk. I have ROCm 6.1.2. maybe the `multi-backend-refactor` branch only supports 6.1 right now.

**Comment by ProtoBelisarius** [comment]
@xzuyn solved it
 
It works with the ROCm/bitsandbytes repo for me with ROCm6.2. I merged the ahead commits from official repo into the ROCm one.

Same as I had already tried, just made an error the first try and merged into the wrong branch. Idk how.

**Comment by ALBIHANY** [comment]
> i updated bitsandbytes and still getting same error about the quant_storage
> 
> AttributeError: 'ForgeParams4bit' object has no attribute 'quant_storage'. Did you mean: 'quant_state'?

Same here i updated bitsandbytes as you said and still having the same error !!!

**Comment by spacedjames** [comment]
This is what worked for me-
ComfyUI Manager > Experimental bottom right corner > install pip packages > bitsandbytes>=0.43.0

**Comment by ALBIHANY** [comment]
> bitsandbytes>=0.43.0

Hey thank you, your tip actually solve that issue, but now i'm dealing with "Error occurred when executing SamplerCustomAdvanced: Allocation on device" issue

**Comment by mapleroyal** [comment]
Has anyone resolved this issue on Apple silicon macs?

**Comment by srv1n** [comment]
> Has anyone resolved this issue on Apple silicon macs? I wonder if all the people giving solutions that worked for them are on windows (or maybe linux).

https://huggingface.co/docs/bitsandbytes/v0.43.3/en/installation

> MacOS support is still a work in progress! Subscribe to this [issue](https://github.com/TimDettmers/bitsandbytes/issues/1020) to get notified about discussions and to track the integration progress.

**Comment by king-ayanda** [comment]
> This is what worked for me- ComfyUI Manager > Experimental bottom right corner > install pip packages > bitsandbytes>=0.43.0

thank you so much😭😭♥
