### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by RYG81** [comfyanonymous/ComfyUI_bitsandbytes_NF4#11]
bin D:\000AI\00ComfyUI\python_embeded\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
Traceback (most recent call last):
  File "D:\000AI\00ComfyUI\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\000AI\00ComfyUI\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4\__init__.py", line 11, in <module>
    from bitsandbytes.nn.modules import Params4bit, QuantState
ImportError: cannot import name 'QuantState' from 'bitsandbytes.nn.modules' (D:\000AI\00ComfyUI\python_embeded\Lib\site-packages\bitsandbytes\nn\modules.py)

Cannot import D:\000AI\00ComfyUI\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4 module for custom nodes: cannot import name 'QuantState' from 'bitsandbytes.nn.modules' (D:\000AI\00ComfyUI\python_embeded\Lib\site-packages\bitsandbytes\nn\modules.py)      
Not found test nodes.

**Comment by RYG81** [comment]
resolved by manually installing bitsandbytes
