### ISSUE TITLE
'types' Import error on startup. Circular import?  Error processing line 1 of /usr/lib/python3/dist-packages/zope.interface-5.4.0-nspkg.pth

### ISSUE THREAD

**Issue by caustiq** [comfyanonymous/ComfyUI_bitsandbytes_NF4#15]
Error processing line 1 of /usr/lib/python3/dist-packages/zope.interface-5.4.0-nspkg.pth:

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.10/site.py", line 192, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/user/Ai/ComfyUI/comfy/types.py", line 1, in <module>
    import torch
  File "/home/user/.local/lib/python3.10/site-packages/torch/__init__.py", line 16, in <module>
    import platform
  File "/usr/lib/python3.10/platform.py", line 117, in <module>
    import re
  File "/usr/lib/python3.10/re.py", line 124, in <module>
    import enum
  File "/usr/lib/python3.10/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/home/user/Ai/ComfyUI/comfy/types.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site.py", line 636, in <module>
    main()
  File "/usr/lib/python3.10/site.py", line 623, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/lib/python3.10/site.py", line 406, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.10/site.py", line 232, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.10/site.py", line 202, in addpackage
    import traceback
  File "/usr/lib/python3.10/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.10/linecache.py", line 8, in <module>
    import functools
  File "/usr/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
  File "/home/user/Ai/ComfyUI/comfy/types.py", line 1, in <module>
    import torch
  File "/home/user/.local/lib/python3.10/site-packages/torch/__init__.py", line 16, in <module>
    import platform
  File "/usr/lib/python3.10/platform.py", line 117, in <module>
    import re
  File "/usr/lib/python3.10/re.py", line 124, in <module>
    import enum
  File "/usr/lib/python3.10/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/home/user/Ai/ComfyUI/comfy/types.py)

**Comment by caustiq** [comment]
Is this the root cause of #12 ?
