### ISSUE TITLE
torch.OutOfMemoryError: Allocation on device

### ISSUE THREAD

**Issue by StableLlama** [comfyanonymous/ComfyUI_bitsandbytes_NF4#17]
Using 16 GB VRAM + plenty of RAM I can easily rund Flux[dev] with everything default (i.e. fp16).
But using this I get an OOM error:
```
!!! Exception during processing!!! Allocation on device 
Traceback (most recent call last):
  File "/home/abc/devel/StableDiffusion/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/abc/devel/StableDiffusion/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/abc/devel/StableDiffusion/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/abc/devel/StableDiffusion/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 612, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "/home/abc/devel/StableDiffusion/ComfyUI/comfy/samplers.py", line 706, in sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds)
  File "/home/abc/devel/StableDiffusion/ComfyUI/comfy/sampler_helpers.py", line 66, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required, minimum_memory_required=minimum_memory_required)
  File "/home/abc/devel/StableDiffusion/ComfyUI/comfy/model_management.py", line 526, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "/home/abc/devel/StableDiffusion/ComfyUI/comfy/model_management.py", line 325, in model_load
    raise e
  File "/home/abc/devel/StableDiffusion/ComfyUI/comfy/model_management.py", line 319, in model_load
    self.real_model = self.model.patch_model_lowvram(device_to=patch_model_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "/home/abc/devel/StableDiffusion/ComfyUI/comfy/model_patcher.py", line 422, in patch_model_lowvram
    self.lowvram_load(device_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "/home/abc/devel/StableDiffusion/ComfyUI/comfy/model_patcher.py", line 406, in lowvram_load
    m.to(device_to)
  File "/home/abc/devel/StableDiffusion/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/home/abc/devel/StableDiffusion/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/home/abc/devel/StableDiffusion/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
  File "/home/abc/devel/StableDiffusion/ComfyUI/custom_nodes/ComfyUI_bitsandbytes_NF4/__init__.py", line 58, in to
    torch.nn.Parameter.to(self, device=device, dtype=dtype, non_blocking=non_blocking),
torch.OutOfMemoryError: Allocation on device 

Got an OOM, unloading all loaded models.
```

**Comment by StableLlama** [comment]
After a complete restart of ComfyUI it's working again.
It seems it didn't remember that it had some VRAM to free.
