### ISSUE TITLE
Node not appearing

### ISSUE THREAD

**Issue by ASilver** [comfyanonymous/ComfyUI_bitsandbytes_NF4#3]
I did a standard Git clone, and have the BnB requirement installed, but the new node does not appear anywhere. Even a search for 'NF4' turns up nothing. ComfyUI is updated already. What am I doing wrong? I tried a completely fresh ComfyUI install, updated also, and same issue.

**Comment by Sefrautic** [comment]
> I did a standard Git clone into the Custom Nodes, and have the BnB requirement installed, but the new node does not appear anywhere. Even a search for 'NF4' turns up nothing. ComfyUI is updated already. What am I doing wrong? I tried a completely fresh ComfyUI install, updated also, and same issue.

Same

**Comment by icey-cold** [comment]
Update your comfyui and make sure the prereqs are installed.  This worked fine for me on the first attempt.  

My one problem was i was on the flux controlnet branch to begin with, but i swapped back to main before starting. Investigate your environments. Something is wrong on your local machines.

**Comment by ivanoff13** [comment]
> the prereqs are installed

how can I check it?

**Comment by ASilver** [comment]
A Discord user clued me in on the problem and solution. If you install bitsandbytes but are using the Portable build, the bitsandbytes package will not be recognized and therefore neither will the node. To fix this, open the Update file

update_comfyui_and_python_dependencies.bat 

and add the following line to it: 

..\python_embeded\python.exe -s -m pip install -U bitsandbytes

Save it and then run it and it will install the dependency for the embedded Python.

**Comment by Sup-Shero** [comment]
how to install requirements please i'm a noob

**Comment by icey-cold** [comment]
> A Discord user clued me in on the problem and solution. If you install bitsandbytes but are using the Portable build, the bitsandbytes package will not be recognized and therefore neither will the node. To fix this, open the Update file

This is expected behaviour from python environments. They're meant to be independent of each other so that dependencies don't conflict. 

> and add the following line to it:
> 
> ..\python_embeded\python.exe -s -m pip install -U bitsandbytes
> 
> Save it and then run it and it will install the dependency for the embedded Python.

You can just run that command in the terminal directly from your root comfyui folder without editing the update bat file and breaking it's purpose.

**Comment by 14422** [comment]
Didn't seem to work for me. I'm on Windows with the portable ComfyUI.

Tried running that BnB installation manually:
`D:\ComfyUI\ComfyUI_windows_portable\python_embeded> python.exe -s -m pip install -U bitsandbytes
Requirement already satisfied: bitsandbytes in c:\users\***\appdata\local\programs\python\python311\lib\site-packages (0.43.3)`

But when I start ComfyUI I get this:
`Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4\__init__.py", line 6, in <module>
    import bitsandbytes
ModuleNotFoundError: No module named 'bitsandbytes'`

So no I cannot find the CheckpointLoaderNF4 node nor can I get it installed with the "Install missing nodes" option.

**Comment by kayselmecnun** [comment]
Same here and not even using the portable version. Updated comfy, BnB was already installed but tried to `pip install bitsandbytes `to be sure.

**Comment by comfyanonymous** [comment]
Node is now in the manager so if you have issues try installing it from there.

**Comment by bejaranoo** [comment]
> Node is now in the manager so if you have issues try installing it from there.

thank you!

**Comment by 14422** [comment]
Should it be found as Bitsandbytes NF4 from the manager?? Can't find anything starting as Bits from mine.
Updated everything and even reinstalled the whole ComfyUI-Manager but still cant' find it.

**Comment by MrUSBEN** [comment]
> Should it be found as Bitsandbytes NF4 from the manager?? Can't find anything starting as Bits from mine. Updated everything and even reinstalled the whole ComfyUI-Manager but still can't find it.

Same

**Comment by bejaranoo** [comment]
> Should it be found as Bitsandbytes NF4 from the manager?? Can't find anything starting as Bits from mine. Updated everything and even reinstalled the whole ComfyUI-Manager but still can't find it.

same

**Comment by boricuapab** [comment]
I hear it's in the dev option in the comfy manager, but I also show another method of doing it here

https://www.youtube.com/watch?v=NkKyu181d_U

There's many solutions to the same problem, hope it helps.

**Comment by 14422** [comment]
> https://www.youtube.com/watch?v=NkKyu181d_U
> 
> There's many solutions to the same problem, hope it helps.

Thanks mate!

This one worked for me:
`..\..\python_embeded\python.exe -s -m pip install -r "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4\requirements.txt"`

**Comment by 2PeteShakur** [comment]
> > https://www.youtube.com/watch?v=NkKyu181d_U
> > There's many solutions to the same problem, hope it helps.
> 
> Thanks mate!
> 
> This one worked for me: `..\..\python_embeded\python.exe -s -m pip install -r "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4\requirements.txt"`

yes this command worked for me too now, the node appears! - just change the path in the command to your own comfyui installed nodes path/dir etc :)

**Comment by polu101** [comment]
> ..\python_embeded\python.exe -s -m pip install -U bitsandbytes

its worked.. thank you

**Comment by tchesket** [comment]
This isn't working for me. I installed bitsandbytes fine, but I am getting an `import triton` error when I try to run comfyui. I'm not understanding how any Windows users are getting this to work if it relies on triton? Can somebody help?

**Comment by tchesket** [comment]
> This isn't working for me. I installed bitsandbytes fine, but I am getting an `import triton` error when I try to run comfyui. I'm not understanding how any Windows users are getting this to work if it relies on triton? Can somebody help?

Ok I got it working, I had to literally comment out all of the triton related stuff in the bitsandbytes __init__.py file. But seems to work like that. Still curious why it was doing that

**Comment by Brostopher** [comment]
Had the same issue with the node but  following the YouTube @boricuapab worked.  Thank you

**Comment by ye-pei-sheng** [comment]
I finded it!
![1](https://github.com/user-attachments/assets/0be43aa0-5310-45e5-99ea-b6a05cb4e5cf)

**Comment by XyW-Max** [comment]
> > A Discord user clued me in on the problem and solution. If you install bitsandbytes but are using the Portable build, the bitsandbytes package will not be recognized and therefore neither will the node. To fix this, open the Update file
> 
> This is expected behaviour from python environments. They're meant to be independent of each other so that dependencies don't conflict.
> 
> > and add the following line to it:
> > ..\python_embeded\python.exe -s -m pip install -U bitsandbytes
> > Save it and then run it and it will install the dependency for the embedded Python.
> 
> You can just run that command in the terminal directly from your root comfyui folder without editing the update bat file and breaking it's purpose.

did it & works,

**Comment by nickapr77** [comment]
> A Discord user clued me in on the problem and solution. If you install bitsandbytes but are using the Portable build, the bitsandbytes package will not be recognized and therefore neither will the node. To fix this, open the Update file
> 
> update_comfyui_and_python_dependencies.bat
> 
> and add the following line to it:
> 
> ..\python_embeded\python.exe -s -m pip install -U bitsandbytes
> 
> Save it and then run it and it will install the dependency for the embedded Python.

This worked for me, thanks.

**Comment by Void2258** [comment]
> Node is now in the manager so if you have issues try installing it from there.

It's not found in the manager browser and if I try to install it from URL it says not allowed.

**Comment by KLL535** [comment]
> > A Discord user clued me in on the problem and solution. If you install bitsandbytes but are using the Portable build, the bitsandbytes package will not be recognized and therefore neither will the node. To fix this, open the Update file
> 
> This is expected behaviour from python environments. They're meant to be independent of each other so that dependencies don't conflict.
> 
> > and add the following line to it:
> > ..\python_embeded\python.exe -s -m pip install -U bitsandbytes
> > Save it and then run it and it will install the dependency for the embedded Python.
> 
> You can just run that command in the terminal directly from your root comfyui folder without editing the update bat file and breaking it's purpose.

NOT work for me
![image](https://github.com/user-attachments/assets/905dd28c-c440-4824-86e2-e7aa250998ab)
