### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by werruww** [comfyanonymous/ComfyUI_bitsandbytes_NF4#52]
upload Workflow????????

**Comment by werruww** [comment]
Flux.forward() missing 1 required positional argument: 'y'

**Comment by werruww** [comment]
[Unsaved MYWorkflow2.json](https://github.com/user-attachments/files/17839520/Unsaved.MYWorkflow2.json)

**Comment by werruww** [comment]
# ComfyUI Error Report
## Error Details
- **Node ID:** 3
- **Node Type:** KSampler
- **Exception Type:** TypeError
- **Exception Message:** Flux.forward() missing 1 required positional argument: 'y'
## Stack Trace
```
  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/content/ComfyUI/nodes.py", line 1454, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)

  File "/content/ComfyUI/nodes.py", line 1421, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,

  File "/content/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "/content/ComfyUI/comfy/samplers.py", line 855, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "/content/ComfyUI/comfy/samplers.py", line 753, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "/content/ComfyUI/comfy/samplers.py", line 740, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "/content/ComfyUI/comfy/samplers.py", line 719, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)

  File "/content/ComfyUI/comfy/samplers.py", line 624, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)

  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)

  File "/content/ComfyUI/comfy/k_diffusion/sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)

  File "/content/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)

  File "/content/ComfyUI/comfy/samplers.py", line 706, in __call__
    return self.predict_noise(*args, **kwargs)

  File "/content/ComfyUI/comfy/samplers.py", line 709, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)

  File "/content/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)

  File "/content/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)

  File "/content/ComfyUI/comfy/model_base.py", line 144, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()

  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)

```
## System Information
- **ComfyUI Version:** v0.3.0-2-g772e620
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 Tesla T4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 15835660288
  - **VRAM Free:** 2532049820
  - **Torch VRAM Total:** 13019119616
  - **Torch VRAM Free:** 31130524

## Logs
```
2024-11-21T03:45:54.504210 - [START] Security scan2024-11-21T03:45:54.504236 - 
2024-11-21T03:45:56.020283 - [DONE] Security scan2024-11-21T03:45:56.020314 - 
2024-11-21T03:45:56.098177 - ## ComfyUI-Manager: installing dependencies done.2024-11-21T03:45:56.098241 - 
2024-11-21T03:45:56.098275 - ** ComfyUI startup time:2024-11-21T03:45:56.098304 -  2024-11-21T03:45:56.098334 - 2024-11-21 03:45:56.0982562024-11-21T03:45:56.098360 - 
2024-11-21T03:45:56.098389 - ** Platform:2024-11-21T03:45:56.098414 -  2024-11-21T03:45:56.098438 - Linux2024-11-21T03:45:56.098464 - 
2024-11-21T03:45:56.098505 - ** Python version:2024-11-21T03:45:56.098530 -  2024-11-21T03:45:56.098554 - 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]2024-11-21T03:45:56.098578 - 
2024-11-21T03:45:56.098603 - ** Python executable:2024-11-21T03:45:56.098627 -  2024-11-21T03:45:56.098651 - /usr/bin/python32024-11-21T03:45:56.098675 - 
2024-11-21T03:45:56.098699 - ** ComfyUI Path:2024-11-21T03:45:56.098723 -  2024-11-21T03:45:56.098746 - /content/ComfyUI2024-11-21T03:45:56.098770 - 
2024-11-21T03:45:56.098815 - ** Log path:2024-11-21T03:45:56.098839 -  2024-11-21T03:45:56.098863 - /content/ComfyUI/comfyui.log2024-11-21T03:45:56.098887 - 
2024-11-21T03:45:56.110261 - 
#######################################################################2024-11-21T03:45:56.110320 - 
2024-11-21T03:45:56.110358 - [ComfyUI-Manager] Starting dependency installation/(de)activation for the extension
2024-11-21T03:45:56.110391 - 
2024-11-21T03:45:56.110603 - Install: pip packages for '/content/ComfyUI/custom_nodes/ComfyUI_bnb_nf4_fp4_Loaders'2024-11-21T03:45:56.110648 - 
2024-11-21T03:45:57.277146 - [SKIP] Downgrading pip package isn't allowed: bitsandbytes (cur=0.44.1)2024-11-21T03:45:57.277228 - 
2024-11-21T03:45:57.277434 - 
[ComfyUI-Manager] Startup script completed.2024-11-21T03:45:57.277491 - 
2024-11-21T03:45:57.277526 - #######################################################################
2024-11-21T03:45:57.277567 - 
2024-11-21T03:45:57.277751 - 
Prestartup times for custom nodes:2024-11-21T03:45:57.277777 - 
2024-11-21T03:45:57.277814 -    2.8 seconds:2024-11-21T03:45:57.277835 -  2024-11-21T03:45:57.277853 - /content/ComfyUI/custom_nodes/ComfyUI-Manager2024-11-21T03:45:57.277873 - 
2024-11-21T03:45:57.277892 - 
2024-11-21T03:45:59.127479 - Total VRAM 15102 MB, total RAM 12979 MB
2024-11-21T03:45:59.127741 - pytorch version: 2.5.1+cu121
2024-11-21T03:45:59.159652 - Set vram state to: NORMAL_VRAM
2024-11-21T03:45:59.159924 - Device: cuda:0 Tesla T4 : cudaMallocAsync
2024-11-21T03:46:00.125102 - Using pytorch cross attention
2024-11-21T03:46:01.196729 - [Prompt Server] web root: /content/ComfyUI/web
2024-11-21T03:46:01.590028 - ### Loading: ComfyUI-Manager (V2.51.9)2024-11-21T03:46:01.590098 - 
2024-11-21T03:46:01.649438 - ### ComfyUI Revision: 2844 [772e620e] | Released on '2024-11-20'2024-11-21T03:46:01.649520 - 
2024-11-21T03:46:01.657204 - Traceback (most recent call last):
  File "/content/ComfyUI/nodes.py", line 2024, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/content/ComfyUI/custom_nodes/.ipynb_checkpoints/__init__.py'

2024-11-21T03:46:01.657746 - Cannot import /content/ComfyUI/custom_nodes/.ipynb_checkpoints module for custom nodes: [Errno 2] No such file or directory: '/content/ComfyUI/custom_nodes/.ipynb_checkpoints/__init__.py'
2024-11-21T03:46:01.703957 - 
Import times for custom nodes:
2024-11-21T03:46:01.704167 -    0.0 seconds: /content/ComfyUI/custom_nodes/example_node.py
2024-11-21T03:46:01.704300 -    0.0 seconds: /content/ComfyUI/custom_nodes/ComfyUI_bnb_nf4_fp4_Loaders
2024-11-21T03:46:01.704431 -    0.0 seconds: /content/ComfyUI/custom_nodes/websocket_image_save.py
2024-11-21T03:46:01.704574 -    0.0 seconds (IMPORT FAILED): /content/ComfyUI/custom_nodes/.ipynb_checkpoints
2024-11-21T03:46:01.704694 -    0.0 seconds: /content/ComfyUI/custom_nodes/ComfyUI-GGUF
2024-11-21T03:46:01.705015 -    0.0 seconds: /content/ComfyUI/custom_nodes/ComfyUI_UNet_bitsandbytes_NF4
2024-11-21T03:46:01.705140 -    0.1 seconds: /content/ComfyUI/custom_nodes/ComfyUI-Manager
2024-11-21T03:46:01.705321 - 
2024-11-21T03:46:01.712675 - Starting server

2024-11-21T03:46:01.713349 - To see the GUI go to: http://127.0.0.1:8188
2024-11-21T03:46:01.723512 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-11-21T03:46:01.723570 - 
2024-11-21T03:46:01.724833 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-11-21T03:46:01.724879 - 
2024-11-21T03:46:01.743208 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-11-21T03:46:01.743262 - 
2024-11-21T03:46:01.779911 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-11-21T03:46:01.779958 - 
2024-11-21T03:46:01.813516 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-11-21T03:46:01.813586 - 
2024-11-21T03:46:07.666358 - got prompt
2024-11-21T03:46:07.998628 - Using pytorch attention in VAE
2024-11-21T03:46:08.001436 - Using pytorch attention in VAE
2024-11-21T03:46:10.763061 - Requested to load MochiTEModel_
2024-11-21T03:46:10.763246 - Loading 1 new model
2024-11-21T03:46:10.771332 - loaded completely 0.0 9083.38671875 True
2024-11-21T03:47:06.842125 - model weight dtype torch.bfloat16, manual cast: torch.float16
2024-11-21T03:47:06.868314 - model_type FLUX
2024-11-21T03:47:06.964065 - Requested to load Flux
2024-11-21T03:47:06.964259 - Loading 1 new model
2024-11-21T03:47:44.232106 - loaded completely 0.0 6388.649485588074 True
2024-11-21T03:47:44.305714 - 
  0% 0/20 [00:00<?, ?it/s]2024-11-21T03:47:44.323809 - 
  0% 0/20 [00:00<?, ?it/s]2024-11-21T03:47:44.323873 - 
2024-11-21T03:47:44.370687 - !!! Exception during processing !!! Flux.forward() missing 1 required positional argument: 'y'
2024-11-21T03:47:44.381417 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 1454, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/content/ComfyUI/nodes.py", line 1421, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/content/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/ComfyUI/comfy/samplers.py", line 855, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/ComfyUI/comfy/samplers.py", line 753, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/ComfyUI/comfy/samplers.py", line 740, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/ComfyUI/comfy/samplers.py", line 719, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/content/ComfyUI/comfy/samplers.py", line 624, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/ComfyUI/comfy/k_diffusion/sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/content/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/content/ComfyUI/comfy/samplers.py", line 706, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/content/ComfyUI/comfy/samplers.py", line 709, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/content/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/content/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/content/ComfyUI/comfy/model_base.py", line 144, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: Flux.forward() missing 1 required positional argument: 'y'

2024-11-21T03:47:44.382055 - Prompt executed in 96.70 seconds
2024-11-21T03:48:22.662537 - got prompt
2024-11-21T03:48:30.640745 - model weight dtype torch.bfloat16, manual cast: torch.float16
2024-11-21T03:48:30.641224 - model_type FLOW
2024-11-21T03:48:30.727883 - Requested to load Flux
2024-11-21T03:48:30.728047 - Loading 1 new model
2024-11-21T03:49:04.717755 - loaded completely 0.0 5854.812986373901 True
2024-11-21T03:49:04.746008 - 
  0% 0/2 [00:00<?, ?it/s]2024-11-21T03:49:04.752364 - 
  0% 0/2 [00:00<?, ?it/s]2024-11-21T03:49:04.752436 - 
2024-11-21T03:49:04.765742 - !!! Exception during processing !!! Flux.forward() missing 1 required positional argument: 'y'
2024-11-21T03:49:04.766141 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 1454, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/content/ComfyUI/nodes.py", line 1421, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/content/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/ComfyUI/comfy/samplers.py", line 855, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/ComfyUI/comfy/samplers.py", line 753, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/ComfyUI/comfy/samplers.py", line 740, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/ComfyUI/comfy/samplers.py", line 719, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/content/ComfyUI/comfy/samplers.py", line 624, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/ComfyUI/comfy/k_diffusion/sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/content/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/content/ComfyUI/comfy/samplers.py", line 706, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/content/ComfyUI/comfy/samplers.py", line 709, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/content/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/content/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/content/ComfyUI/comfy/model_base.py", line 144, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: Flux.forward() missing 1 required positional argument: 'y'

2024-11-21T03:49:04.766772 - Prompt executed in 42.10 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":14,"nodes":[{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":12}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"]},{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":13}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":7,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":11}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":[1451,189],"size":[210,58],"flags":{},"order":8,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":13,"type":"VAELoader","pos":[38,499],"size":[315,58],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[11],"slot_index":0}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["sdxl_vae.safetensors"]},{"id":14,"type":"CLIPLoader","pos":[-14,665],"size":[315,82],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[12,13],"slot_index":0}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["t5xxl_fp16.safetensors","stable_diffusion"]},{"id":3,"type":"KSampler","pos":[609,99],"size":[315,262],"flags":{},"order":6,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":14},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[843118449862996,"randomize",2,8,"euler","normal",1]},{"id":15,"type":"UNETLoaderNF4","pos":[17,281],"size":[315,58],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[14],"slot_index":0}],"properties":{"Node name for S&R":"UNETLoaderNF4"},"widgets_values":["flux1-schnell-bnb-nf4-unet.safetensors"]}],"links":[[2,5,0,3,3,"LATENT"],[4,6,0,3,1,"CONDITIONING"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[9,8,0,9,0,"IMAGE"],[11,13,0,8,1,"VAE"],[12,14,0,6,0,"CLIP"],[13,14,0,7,0,"CLIP"],[14,15,0,3,0,"MODEL"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[-12,-1]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
