### ISSUE TITLE
load_checkpoint_guess_config() got an unexpected keyword argument 'model_options'

### ISSUE THREAD

**Issue by specblades** [comfyanonymous/ComfyUI_bitsandbytes_NF4#6]
Error occurred when executing CheckpointLoaderNF4:

load_checkpoint_guess_config() got an unexpected keyword argument 'model_options'

File "S:\ComfyUImain\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "S:\ComfyUImain\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "S:\ComfyUImain\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "S:\ComfyUImain\custom_nodes\ComfyUI_bitsandbytes_NF4\__init__.py", line 176, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"), model_options={"custom_operations": OPS})

**Comment by efonte** [comment]
Make sure your ComfyUI is updated.

**Comment by Mohsyn** [comment]
same issue - comfyui is updated

**Comment by TenaciousDean** [comment]
Same issue here

**Comment by nokai** [comment]
Same issue here
All updated

**Comment by wtesler** [comment]
Same

**Comment by wtesler** [comment]
I had to do a more complete re-install of ComfyUI. Copying over my checkpoints  and custom nodes etc... then it worked.

**Comment by Mindrix95** [comment]
Just run ComfyUI\update\update_comfyui.bat

**Comment by Kallamamran** [comment]
Everything updated here. Same error

**Comment by AllEyEsOnMe9977** [comment]
same same

**Comment by MayoPonyo** [comment]
> Just run ComfyUI\update\update_comfyui.bat

Running the update.bat over using manager fixed the issue. Thank you.

**Comment by AllEyEsOnMe9977** [comment]
> > Just run ComfyUI\update\update_comfyui.bat
> 
> Running the update.bat over using manager fixed the issue. But the result are extremely blurry.

i get this error while running it:
Traceback (most recent call last):
  File "C:\Model Launcher\update\update.py", line 53, in <module>
    repo.stash(ident)
  File "C:\Model Launcher\python_embeded\Lib\site-packages\pygit2\repository.py", line 1080, in stash
    check_error(err)
  File "C:\Model Launcher\python_embeded\Lib\site-packages\pygit2\errors.py", line 66, in check_error
    raise GitError(message)
_pygit2.GitError: cannot create a tree from a not fully merged index.

**Comment by AllEyEsOnMe9977** [comment]
> > > Just run ComfyUI\update\update_comfyui.bat
> > 
> > 
> > Running the update.bat over using manager fixed the issue. But the result are extremely blurry.
> 
> i get this error while running it: Traceback (most recent call last): File "C:\Model Launcher\update\update.py", line 53, in repo.stash(ident) File "C:\Model Launcher\python_embeded\Lib\site-packages\pygit2\repository.py", line 1080, in stash check_error(err) File "C:\Model Launcher\python_embeded\Lib\site-packages\pygit2\errors.py", line 66, in check_error raise GitError(message) _pygit2.GitError: cannot create a tree from a not fully merged index.

nevermind, fixed it:
aborted merge
git poll
run upbate.bat

**Comment by ka1tte** [comment]
> same issue - comfyui is updated

https://github.com/comfyanonymous/ComfyUI/blob/e60e19b175f93f2c8fac037063de9f13259be9d4/comfy/sd.py#L509
Make sure the load_checkpoint_guess_config function in your local code contains the model_options parameter, otherwise please update the code.
